r_back_end:
    url: http://127.0.0.1:9799/exec/
    image_name: srp33/codebuddy_r
    memory_allowed_mb: 100
    timeout_seconds: 30
    code_completion_path: ace/mode/r
    output_types:
        - jpg
        - txt
