mode: development
domain: codebuddy.byu.edu
db_name: CodeBuddy.db
allowed_external_urls:
  - https://geomoer.github.io/moer-base-r/assets/data/cheatsheets/base-r.pdf
  - https://github.com/rstudio/cheatsheets/raw/master/data-import.pdf
  - https://github.com/rstudio/cheatsheets/raw/master/data-visualization.pdf
  - https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf
  - https://github.com/rstudio/cheatsheets/raw/master/tidyr.pdf 
  - https://github.com/rstudio/cheatsheets/raw/master/strings.pdf
  - https://github.com/rstudio/cheatsheets/raw/master/factors.pdf
  - https://github.com/rstudio/cheatsheets/raw/master/lubridate.pdf
back_ends:
    free_response:
        description: Please write an answer based on the instructions provided.
        code_completion_path: ace/mode/text
        output_types:
            txt: |-
                Text
    any_response:
        description: Please write an answer based on the instructions provided. Any response will be given credit.
        code_completion_path: ace/mode/text
        output_types:
            txt: |-
                Text
    r:
        description: Please write R code based on the instructions provided.
        image_name: srp33/codebuddy_r
        memory_allowed_mb: 100
        timeout_seconds: 120
        code_completion_path: ace/mode/r
        output_types:
            jpg: |-
                Image (ggplot2)
            txt: |-
                Text

    python:
        description: Please write Python code based on the instructions provided.
        image_name: srp33/codebuddy_python
        memory_allowed_mb: 100
        timeout_seconds: 60
        code_completion_path: ace/mode/python
        output_types:
            jpg: |-
                Image (matplotlib or seaborn)
            txt: |-
                Text
    python_script:
        description: Please write Python code based on the instructions provided. Your code will be stored in a script called code.py.
        image_name: srp33/codebuddy_python_script
        memory_allowed_mb: 100
        timeout_seconds: 60
        code_completion_path: ace/mode/python
        output_types:
            jpg: |-
                Image (matplotlib or seaborn)
            txt: |-
                Text
    bash:
        description: bash commands
        image_name: srp33/codebuddy_bash
        memory_allowed_mb: 100
        timeout_seconds: 60
        code_completion_path: ace/mode/plain_text
        output_types:
            txt: |-
                Text (standard out)
