mode: development
domain: codebuddy.byu.edu
db_name: CodeBuddy.db
back_ends:
    free_response:
        description: Please write an answer based on the instructions provided.
        code_completion_path: ace/mode/text
        output_types:
            txt: |-
                Text
    any_response:
        description: Please write an answer based on the instructions provided. Any response will be given credit.
        code_completion_path: ace/mode/text
        output_types:
            txt: |-
                Text
    r:
        description: Please write R code based on the instructions provided.
        image_name: srp33/codebuddy_r
        memory_allowed_mb: 100
        timeout_seconds: 30
        code_completion_path: ace/mode/r
        output_types:
            jpg: |-
                Image (base graphics or ggplot2)
            txt: |-
                Text
    python:
        description: Please write Python code based on the instructions provided.
        image_name: srp33/codebuddy_python
        memory_allowed_mb: 100
        timeout_seconds: 30
        code_completion_path: ace/mode/python
        output_types:
            jpg: |-
                Image (matplotlib or seaborn)
            txt: |-
                Text
    bash:
        description: bash commands
        image_name: srp33/codebuddy_bash
        memory_allowed_mb: 100
        timeout_seconds: 30
        code_completion_path: ace/mode/plain_text
        output_types:
            txt: |-
                Text (standard out)
