description: Please write Python code based on the instructions provided.
memory_allowed_mb: 500
timeout_seconds: 60
code_completion_path: ace/mode/python
output_types:
    txt: |-
        Text
solution_instructions: ""
solution_example: "def add_numbers(x, y):\n\treturn(x + y)"
verification_instructions: "Write your verification code in Python."
verification_example: "with open('code') as student_code:\n\tfor line in student_code:\n\t\tif 'len(' in line:\n\t\t\tprint('Error: len() function not permitted in this exercise')\n\t\t\tbreak"
test_instructions: ""
after_test_example: "print(add_numbers(2, 3))"