description: Please write R code based on the instructions provided.
memory_allowed_mb: 500
timeout_seconds: 60
code_completion_path: ace/mode/r
output_types:
    jpg: |-
        Image (ggplot2)
    txt: |-
        Text
solution_instructions: ""
solution_example: "# R example code\nadd_numbers <- function(x, y) {\n\treturn(x + y)\n}"
verification_instructions: "Write your verification code in R."
verification_example: "connection <- file('code')\nopen(connection)\nline <- readLines(connection, n=1)\nsearch <- 'len'\n\nwhile(length(line) > 0) {\n\tif (grepl(tolower(search), tolower(line))) {\n\t\tprint('Error: len() function not allowed in this exercise')\n\t\tbreak\n\t}\n\n\tline <- readLines(connection, n=1)\n}\n\nclose(connection)"
test_instructions: ""
after_test_example: "print(add_numbers(2, 3))"