description: Please write Python code based on the instructions provided. Your code will be stored in a script called code.py.
memory_allowed_mb: 500
timeout_seconds: 60
code_completion_path: ace/mode/python
output_types:
    jpg: |-
        Image (matplotlib or seaborn)
    txt: |-
        Text
solution_instructions: "For this type of exercise, write your solution in Python. You will write bash commands that execute your Python script under the Tests section."
solution_example: "import sys\n\nprint(sys.argv[1])"
verification_instructions: "Write your verification code in bash."
verification_example: "FIND='#'\nwhile read -r line;\n\tdo\n\tif grep -q \"$FIND\" <<< \"$line\"; then\n\t\techo \"Error: $FIND operator not allowed in this exercise\"\n\t\tbreak\"\tfi\ndone < code"
test_instructions: "Each test will consist of a bash script that will invoke the student's solution code (saved as 'code.py')."
after_test_example: "python code.py \"Hello world!\""