description: Please write C code based on the instructions provided.
memory_allowed_mb: 500
timeout_seconds: 60
code_completion_path: ace/mode/C_Cpp
output_types:
    txt: |-
        Text
solution_instructions: ""
solution_example: "#include <stdio.h>\n\nint add(int a, int b) {\n    int sum = a + b;\n    return sum;\n}"
verification_instructions: "Write your verification code in Python (not C)."
verification_example: "with open('code') as student_code:\n\tfor line in student_code:\n\t\tif 'len(' in line:\n\t\t\tprint('Error: len() function not permitted in this exercise')\n\t\t\tbreak"
test_instructions: ""
after_test_example: "int main() {\n    int num1 = 10;\n    int num2 = 20;\n    int result = add(num1, num2);\n    printf('The sum is: %d\n', result);\n    return 0;\n};"